### GENERAL SETTINGS ###

# Site settings
title: WOW Games
description: "We make games not just for your entertainment, but for your inner nerd as well."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0079b5" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Priyank Patel
    position: Engine Developer
    img: team01.png
    social:
      - title: envelope #use for email address
        url: mailto:pnpatel2@uci.edu

  - name: Gary Pan
    position: Expert Programmer
    img: team04.png
    social:
      - title: envelope #use for email address
        url: mailto:gpan2@uci.edu

  - name: DK Nguyen
    position: Web Designer
    img: team02.png
    social:
      - title: envelope #use for email address
        url: mailto:dkknguyen23@gmail.com

  - name: Jacob Marello
    position: Script Writer
    img: team05.png
    social:
      - title: envelope #use for email address
        url: mailto:jmarello@uci.edu

  - name: Jimmy Liu
    position: Marketing Manager
    img: team06.png
    social:
      - title: envelope #use for email address
        url: mailto:jimml10@uci.edu

  - name: Darren Lieu
    position: Assistant to the Project Manager
    img: team03.png
    social:
      - title: envelope #use for email address
        url: mailto:lieud1@uci.edu

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We make games not just for your entertainment, but for your inner nerd as well."


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
# social:
#   - title: dribbble
#     url:
#   - title: facebook
#     url:
#   - title: twitter
#     url:
#   - title: instagram
#     url:
#   - title: tumblr
#     url:
#
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
# address:
#   - lines:
#     - Some Ave, 987,
#     - 23890, New York,
#     - United States.
# email: hello@solidtheme.com
# tel: +34 8493-4893
